server.port=9091
spring.application.name=load-balanced-gateway
spring.cloud.gateway.routes[0].id=load_balanced_route
spring.cloud.gateway.routes[0].uri=lb://example-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/loadbalanced/**
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
