server:
  port: 8086

spring:
  application:
    name: resilient-gateway
  cloud:
    gateway:
      routes:
        - id: resilient_route
          uri: http://localhost:8080
          predicates:
            - Path=/resilient/**
          filters:
            - name: CircuitBreaker
              args:
                name: exampleCircuitBreaker
                fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    instances:
      exampleCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
