CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID NUMBER,
    LogDate DATE,
    Amount NUMBER,
    TransactionType VARCHAR2(10)
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, AccountID, LogDate, Amount, TransactionType)
    VALUES (:NEW.TransactionID, :NEW.AccountID, SYSDATE, :NEW.Amount, :NEW.TransactionType);
END;
/